{% set name = "hsluv" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf7d38b68e3e21f897c3982ba509d4a5f26d3833275ff24bc40fb3268083b782

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    # for long_description_content_type
    - setuptools >=38.6.0

test:
  imports:
    - hsluv

about:
  home: https://github.com/hsluv/hsluv-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python implementation of HSLuv (revision 4).

extra:
  recipe-maintainers:
    - hmaarrfk
