{% set name = "hsluv" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ffea98b29c6a7d25a4296eed400b491c89fd89365806a0f646ede44c043727fa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    # for long_description_content_type
    - setuptools >=38.6.0

test:
  imports:
    - hsluv

about:
  home: https://github.com/hsluv/hsluv-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python implementation of HSLuv (revision 4).

extra:
  recipe-maintainers:
    - hmaarrfk
