{% set name = "hsluv" %}
{% set version = "5.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2281f946427a882010042844a38c7bbe9e0d0aaf9d46babe46366ed6f169b72e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools >=38.6.0
  run:
    - python
    # for long_description_content_type
    - setuptools >=38.6.0

test:
  source_files:
    - tests
  imports:
    - hsluv
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/hsluv/hsluv-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python implementation of HSLuv (revision 4).
  description: |
    HSLuv is a human-friendly alternative to HSL implemented
    in Python (revision 4).
  doc_url: https://github.com/hsluv/hsluv-python
  dev_url: https://github.com/hsluv/hsluv-python

extra:
  recipe-maintainers:
    - hmaarrfk